name: MoveableChest
main: com.gabsoftware.MoveableChest.MoveableChest
version: 0.1
commands:
  mc:
    description: This is the main command.
    usage: /mc
    permission: MoveableChest.mc
    permission-message: You don't have the permission to use this command.